baseURL = 'https://indie.tw'
languageCode = 'zh-TW'
title = 'indieveloper'
hasCJKLanguage = true
relativeURLs = true

ignoreFiles = ['/node_modules/*']

[params]
mainSections = ['docs']
subTitle = '獨立開發者'
timeFormat = "2006.01.02 15:04"

[menu]
    [[menu.main]]
        name = 'docs'
        url = '/docs/'
        weight = 10
        
#    [[menu.main]]
#        name = 'blog'
#        url = '/blog/'
#        weight = 20

    [[menu.main]]
        name = 'github'
        url = 'https://github.com/lancatlin/indie.tw'
        weight = 30
